import type { CalculationInput, Country, Deal } from "./types";
import { SWISS_FIRST_MORTGAGE_LTV_PCT } from "./repayment";

/** Sensible local defaults per market. */
export function defaultInput(country: Country): CalculationInput {
  const ch = country === "CH";
  return {
    purchasePrice: ch ? 1_000_000 : 400_000,
    estimatedMarketValue: ch ? 1_000_000 : 400_000,
    areaSqm: 80,

    transferTaxPct: ch ? 1.5 : 5.0,
    notaryPct: ch ? 0.2 : 1.5,
    landRegistryPct: ch ? 0.25 : 0.5,
    brokerPct: ch ? 2.0 : 3.57,
    mortgageFeePct: ch ? 0.25 : 0.5,
    otherCostsFixed: 0,
    renovationBudget: 0,

    equity: ch ? 250_000 : 100_000,
    mortgageSystem: "annuity",
    interestPhases: [
      { years: 10, ratePct: ch ? 3.1 : 3.8 },
      { years: 15, ratePct: ch ? 3.6 : 4.3 },
    ],
    loanTermYears: 25,
    interestOnlyYears: 0,

    firstMortgageLtvPct: SWISS_FIRST_MORTGAGE_LTV_PCT,
    mandatoryAmortizationYears: 15,
    optionalAmortizationYears: 0,
    mandatoryAmortizationMonthly: 0,
    voluntaryFirstMortgagePrincipalMonthly: 0,

    monthlyRent: ch ? 3_000 : 1_400,
    additionalIncomeMonthly: 0,
    vacancyPct: 3,
    targetYieldPct: ch ? 3.5 : 4.5,

    maintenancePctOfValue: 1.0,
    nebenkostenMonthly: ch ? 250 : 120,
    managementMonthly: ch ? 70 : 40,
    propertyTaxAnnual: ch ? 1_200 : 500,
    renovationReserveMonthly: ch ? 80 : 50,

    appreciationPct: 1.5,
    inflationPct: 1.2,
    rentGrowthPct: 1.2,
    investmentReturnPct: 5.0,

    projectionYears: 30,
  };
}

export function blankInput(): CalculationInput {
  return {
    purchasePrice: 0,
    estimatedMarketValue: 0,
    areaSqm: 0,
    transferTaxPct: 0,
    notaryPct: 0,
    landRegistryPct: 0,
    brokerPct: 0,
    mortgageFeePct: 0,
    otherCostsFixed: 0,
    renovationBudget: 0,
    equity: 0,
    mortgageSystem: "annuity",
    interestPhases: [{ years: 10, ratePct: 0 }],
    loanTermYears: 25,
    interestOnlyYears: 0,
    firstMortgageLtvPct: SWISS_FIRST_MORTGAGE_LTV_PCT,
    mandatoryAmortizationYears: 15,
    optionalAmortizationYears: 0,
    mandatoryAmortizationMonthly: 0,
    voluntaryFirstMortgagePrincipalMonthly: 0,
    monthlyRent: 0,
    additionalIncomeMonthly: 0,
    vacancyPct: 0,
    targetYieldPct: 0,
    maintenancePctOfValue: 0,
    nebenkostenMonthly: 0,
    managementMonthly: 0,
    propertyTaxAnnual: 0,
    renovationReserveMonthly: 0,
    appreciationPct: 0,
    inflationPct: 0,
    rentGrowthPct: 0,
    investmentReturnPct: 0,
    projectionYears: 30,
  };
}

/** Default placeholder address shown for new deals until edited. */
export const SAMPLE_ADDRESS = {
  name: "Muster Adresse",
  address: "Musterstrasse 1",
  zip: "8000",
  city: "Zürich",
} as const;

/** Backfill newer input fields on deals saved before a schema change. */
export function normalizeInput(input: Partial<CalculationInput>): CalculationInput {
  const base = blankInput();
  return {
    ...base,
    ...input,
    interestPhases: input.interestPhases?.length ? input.interestPhases : base.interestPhases,
    firstMortgageLtvPct: input.firstMortgageLtvPct ?? SWISS_FIRST_MORTGAGE_LTV_PCT,
    mandatoryAmortizationYears: input.mandatoryAmortizationYears ?? 15,
    optionalAmortizationYears: input.optionalAmortizationYears ?? 0,
    mandatoryAmortizationMonthly: input.mandatoryAmortizationMonthly ?? 0,
    voluntaryFirstMortgagePrincipalMonthly: input.voluntaryFirstMortgagePrincipalMonthly ?? 0,
  };
}

export function formatDealAddress(deal: Pick<Deal, "address" | "zip" | "city" | "country">): string {
  const parts = [deal.address, [deal.zip, deal.city].filter(Boolean).join(" "), deal.country].filter(Boolean);
  return parts.join(", ");
}

/** A new deal with no pre-filled assumptions — for inline creation in the metrics view. */
export function blankDeal(country: Country = "CH"): Deal {
  const now = Date.now();
  return {
    id: crypto.randomUUID(),
    name: SAMPLE_ADDRESS.name,
    address: SAMPLE_ADDRESS.address,
    zip: SAMPLE_ADDRESS.zip,
    city: SAMPLE_ADDRESS.city,
    country,
    currency: country === "CH" ? "CHF" : "EUR",
    propertyType: "Apartment",
    yearBuilt: 0,
    rooms: 0,
    notes: "",
    mapX: 0.2 + Math.random() * 0.6,
    mapY: 0.2 + Math.random() * 0.6,
    photoHue: Math.floor(Math.random() * 360),
    input: blankInput(),
    createdAt: now,
    updatedAt: now,
  };
}

export function emptyDeal(country: Country = "CH"): Deal {
  const now = Date.now();
  return {
    id: crypto.randomUUID(),
    name: "",
    address: "",
    zip: "",
    city: "",
    country,
    currency: country === "CH" ? "CHF" : "EUR",
    propertyType: "Apartment",
    yearBuilt: 1990,
    rooms: 3.5,
    notes: "",
    mapX: 0.5,
    mapY: 0.5,
    photoHue: Math.floor(Math.random() * 360),
    input: defaultInput(country),
    createdAt: now,
    updatedAt: now,
  };
}

export const SEED_DEALS: Deal[] = [
  {
    id: "bellevue-42-zuerich",
    name: "Bellevue 42",
    address: "Bellevue 42",
    zip: "8001",
    city: "Zürich",
    country: "CH",
    currency: "CHF",
    propertyType: "Apartment",
    yearBuilt: 1992,
    rooms: 3.5,
    notes: "",
    mapX: 0.62,
    mapY: 0.28,
    lat: 47.3668,
    lng: 8.5451,
    photoHue: 145,
    createdAt: Date.now() - 86_400_000 * 12,
    updatedAt: Date.now() - 3_600_000,
    input: normalizeInput({
      purchasePrice: 1_240_000,
      estimatedMarketValue: 1_210_000,
      areaSqm: 78,
      transferTaxPct: 1.5,
      notaryPct: 0.1,
      landRegistryPct: 0.1,
      brokerPct: 2.0,
      mortgageFeePct: 0.25,
      otherCostsFixed: 0,
      renovationBudget: 40_000,
      equity: 318_650,
      mortgageSystem: "annuity",
      interestPhases: [
        { years: 10, ratePct: 3.1 },
        { years: 15, ratePct: 3.7 },
      ],
      loanTermYears: 25,
      interestOnlyYears: 0,
      monthlyRent: 2_450,
      additionalIncomeMonthly: 0,
      vacancyPct: 3,
      targetYieldPct: 3.5,
      maintenancePctOfValue: 0.1,
      nebenkostenMonthly: 250,
      managementMonthly: 70,
      propertyTaxAnnual: 1_200,
      renovationReserveMonthly: 83,
      appreciationPct: 1.5,
      inflationPct: 1.8,
      rentGrowthPct: 1.2,
      investmentReturnPct: 5.0,
      projectionYears: 30,
    }),
  },
  {
    id: "rheingasse-18-basel",
    name: "Rheingasse 18",
    address: "Rheingasse 18",
    zip: "4058",
    city: "Basel",
    country: "CH",
    currency: "CHF",
    propertyType: "Apartment",
    yearBuilt: 1978,
    rooms: 2.5,
    notes: "",
    mapX: 0.33,
    mapY: 0.2,
    lat: 47.5606,
    lng: 7.5906,
    photoHue: 30,
    createdAt: Date.now() - 86_400_000 * 30,
    updatedAt: Date.now() - 86_400_000 * 2,
    input: normalizeInput({
      purchasePrice: 620_000,
      estimatedMarketValue: 655_000,
      areaSqm: 58,
      transferTaxPct: 1.8,
      notaryPct: 0.3,
      landRegistryPct: 0.25,
      brokerPct: 0,
      mortgageFeePct: 0.25,
      otherCostsFixed: 1_500,
      renovationBudget: 12_000,
      equity: 165_000,
      mortgageSystem: "annuity",
      interestPhases: [
        { years: 10, ratePct: 2.9 },
        { years: 15, ratePct: 3.5 },
      ],
      loanTermYears: 25,
      interestOnlyYears: 0,
      monthlyRent: 2_850,
      additionalIncomeMonthly: 120,
      vacancyPct: 2,
      targetYieldPct: 3.8,
      maintenancePctOfValue: 1.1,
      nebenkostenMonthly: 190,
      managementMonthly: 60,
      propertyTaxAnnual: 900,
      renovationReserveMonthly: 70,
      appreciationPct: 1.6,
      inflationPct: 1.2,
      rentGrowthPct: 1.3,
      investmentReturnPct: 5.0,
      projectionYears: 30,
    }),
  },
  {
    id: "leopoldstrasse-88-muenchen",
    name: "Leopoldstrasse 88",
    address: "Leopoldstrasse 88",
    zip: "80802",
    city: "München",
    country: "DE",
    currency: "EUR",
    propertyType: "Multi-family",
    yearBuilt: 1965,
    rooms: 3,
    notes: "",
    mapX: 0.78,
    mapY: 0.62,
    lat: 48.1589,
    lng: 11.5847,
    photoHue: 210,
    createdAt: Date.now() - 86_400_000 * 45,
    updatedAt: Date.now() - 86_400_000 * 5,
    input: normalizeInput({
      purchasePrice: 890_000,
      estimatedMarketValue: 905_000,
      areaSqm: 210,
      transferTaxPct: 3.5,
      notaryPct: 1.5,
      landRegistryPct: 0.5,
      brokerPct: 3.57,
      mortgageFeePct: 0.5,
      otherCostsFixed: 2_000,
      renovationBudget: 60_000,
      equity: 280_000,
      mortgageSystem: "annuity",
      interestPhases: [
        { years: 10, ratePct: 3.8 },
        { years: 20, ratePct: 4.4 },
      ],
      loanTermYears: 30,
      interestOnlyYears: 0,
      monthlyRent: 4_200,
      additionalIncomeMonthly: 150,
      vacancyPct: 4,
      targetYieldPct: 4.5,
      maintenancePctOfValue: 1.2,
      nebenkostenMonthly: 380,
      managementMonthly: 160,
      propertyTaxAnnual: 1_900,
      renovationReserveMonthly: 250,
      appreciationPct: 2.0,
      inflationPct: 1.8,
      rentGrowthPct: 1.8,
      investmentReturnPct: 5.5,
      projectionYears: 30,
    }),
  },
  {
    id: "schoeneggstrasse-12-zuerich",
    name: "Schöneggstrasse 12",
    address: "Schöneggstrasse 12",
    zip: "8004",
    city: "Zürich",
    country: "CH",
    currency: "CHF",
    propertyType: "House",
    yearBuilt: 2004,
    rooms: 5.5,
    notes: "",
    mapX: 0.58,
    mapY: 0.33,
    lat: 47.3735,
    lng: 8.5212,
    photoHue: 275,
    createdAt: Date.now() - 86_400_000 * 8,
    updatedAt: Date.now() - 86_400_000,
    input: normalizeInput({
      purchasePrice: 1_650_000,
      estimatedMarketValue: 1_600_000,
      areaSqm: 142,
      transferTaxPct: 1.5,
      notaryPct: 0.2,
      landRegistryPct: 0.2,
      brokerPct: 2.4,
      mortgageFeePct: 0.25,
      otherCostsFixed: 0,
      renovationBudget: 0,
      equity: 380_000,
      mortgageSystem: "annuity",
      interestPhases: [
        { years: 5, ratePct: 3.4 },
        { years: 20, ratePct: 4.0 },
      ],
      loanTermYears: 25,
      interestOnlyYears: 0,
      monthlyRent: 3_950,
      additionalIncomeMonthly: 0,
      vacancyPct: 3,
      targetYieldPct: 3.5,
      maintenancePctOfValue: 0.9,
      nebenkostenMonthly: 320,
      managementMonthly: 90,
      propertyTaxAnnual: 1_600,
      renovationReserveMonthly: 120,
      appreciationPct: 1.4,
      inflationPct: 1.2,
      rentGrowthPct: 1.1,
      investmentReturnPct: 5.0,
      projectionYears: 30,
    }),
  },
];
